/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class parses the response for Equifax
Development Date : 10/03/2022
Last Modified Date : 18/05/2022
****************************************************************************************************/
global class NextGenResponseDetailHelper {
	public String status;
    public String applicationName;
    public String detailedStatus;
}